#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Remove extracted features (keep STL geometry)
rm -rf constant/extendedFeatureEdgeMesh
rm -f constant/triSurface/*.eMesh
rm -f constant/triSurface/*.obj

# checkMesh -writeFields leftovers (must not outlive a remesh)
rm -f constant/nonOrthoAngle

#------------------------------------------------------------------------------
